### ISSUE TITLE
how to make the riemann-sumd work with the check-mk

### ISSUE THREAD

**Issue by huhongbo** [bmhatfield/riemann-sumd#12]
check-mk is more advanced project than nagios check,
is possible to let riemann-sumd work with check-mk?

**Comment by bmhatfield** [comment]
Hi @huhongbo - it's been more than a year since you filed this issue, but I'd still like to try and answer your question as best I can. After reviewing check_mk, I'm not sure I fully understand where in it's architecture you'd like Riemann-Sumd to fit in.

To be clear: the intent of riemann-sumd is to schedule tasks (and bridge their output) and send the events to Riemann.

Could you further expand on the idea of your use case? Alternatively, I am happy to close this issue if a year's delayed response means you've moved on :-)
